
detalii_primarii ={
	"ALEXANDRU IOAN CUZA": {
		"partid": "PSD",
		"type": "Comuna",
		"primar": "Baciu Vasile Cornelus",
		"raspuns": "./raspunsuri_primarii/Al.I.Cuza.pdf",
		"s_p": 5800,
		"s_vp": 4350,
		"s_s": null,
		"c_p": 4,
		"c_vp": 3,
		"c_s": 0,
		"populatie": 2917,
		"site": "http://primaria-aicuza.xhost.ro/prezentare.htm"
	},
	"ANDRIESENI": {
		"partid": "PNL",
		"type": "Comuna",
		"primar": "Maricel Turcu",
		"raspuns": null,
		"c_p": 4.5,
		"c_vp": 3.5,
		"populatie": 4422,
		"site": "http://www.primariaandrieseni.ro/",
		"c_s": 0
	},
	"ARONEANU": {
		"partid": "PNL",
		"type": "Comuna",
		"primar": "Moruzi Benoni",
		"raspuns": null,
		"c_p": 4.5,
		"populatie": 3747,
		"site": "http://www.comunaaroneanu.ro/",
		"c_vp": 0,
		"c_s": 0
	},
	"BALS": {
		"partid": "PSD",
		"type": "Comuna",
		"primar": "Cibotaru Constantin",
		"raspuns": ["./raspunsuri_primarii/bals1.pdf", "./raspunsuri_primarii/bals2.pdf"],
		"s_p": 6525,
		"s_vp": 5075,
		"s_s": 5060,
		"c_p": 4.5,
		"c_vp": 3.5,
		"c_s": 3.49,
		"populatie": 3640,
		"site": "http://primariacomuneibals.ro/index.html"
	},
	"BALTATI": {
		"partid": "PSD",
		"type": "Comuna",
		"primar": "Astefanei Vasile",
		"raspuns": "./raspunsuri_primarii/Baltati.pdf",
		"s_p": 9063,
		"c_p": 6.25,
		"c_vp": 4,
		"s_s": 5786,
		"c_s": 0,
		"populatie": 5626,
		"s_vp": 5800,
		"site": "http://www.primariabaltati.ro/"
	},
	"BARNOVA": {
		"partid": "PSD",
		"type": "Comuna",
		"primar": "Balan Mihai",
		"raspuns": "./raspunsuri_primarii/Barnova.pdf",
		"s_p": 7250,
		"c_p": 5,
		"s_vp": 5800,
		"c_vp": 4,
		"s_s": 5800,
		"c_s": 4,
		"populatie": 11545,
		"site": "http://primariabarnova.ro/"
	},
	"BELCESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": null,
		"primar": "Ciobanita Constantin",
		"populatie": 6160,
		"site": "http://primaria.belcesti.ro/",
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"BIVOLARI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"primar": "Teodorescu Dumitru-liviu",
		"populatie": 4338,
		"site": "http://comunabivolari.ro/",
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"BRAESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Braesti.PDF",
		"primar": "Butnaru Vasile",
		"populatie": 3197,
		"c_p": 4.5,
		"s_p": 6525,
		"s_vp": 5075,
		"c_s": 2.6,
		"s_s": 3770,
		"site": "http://www.primariabraesti.ro/",
		"c_vp": 0
	},
	"BUTEA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Butea.pdf",
		"primar": "Anti Anton",
		"c_p": 4.5,
		"s_p": 6525,
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3,
		"s_s": 4350,
		"populatie": 4336,
		"site": "http://primaria-butea.xyz/"
	},
	"CEPLENITA": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Ceplenita.xls",
		"primar": "Laiu Dumitru",
		"populatie": 4418,
		"c_p": 5.625,
		"s_p": 8156,
		"c_vp": 4.375,
		"s_vp": 6344,
		"c_s": 3.48,
		"s_s": 5046,
		"site": "http://www.primariaceplenita.ro/"
	},
	"CIOHORANI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Ciohorani.pdf",
		"primar": "Simion Ticu",
		"c_p": 5,
		"s_p": 7250,
		"c_vp": 3.75,
		"s_vp": 5438,
		"s_s": 4350,
		"c_s": 3,
		"populatie": 2015,
		"site": "http://www.comunaciohorani.ro/"
	},
	"CIORTESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Ciortesti.xls",
		"primar": "Apostol Alina",
		"c_p": 4.5,
		"s_p": 6525,
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.45,
		"s_s": 5003,
		"populatie": 4324,
		"site": "http://www.primariaciortesti.ro/"
	},
	"CIUREA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": ["./raspunsuri_primarii/Ciurea 1.bmp", "./raspunsuri_primarii/Ciurea 2.bmp", "./raspunsuri_primarii/Ciurea 3.bmp", "./raspunsuri_primarii/Ciurea 4.bmp", "./raspunsuri_primarii/Ciurea 5.bmp", "./raspunsuri_primarii/Ciurea 6.bmp", "./raspunsuri_primarii/Ciurea 7.bmp"],
		"primar": "Lupu Catalin",
		"s_p": 7975,
		"c_p": 5.5,
		"s_vp": 6525,
		"c_vp": 4.5,
		"s_s": 5583,
		"c_s": 3.85,
		"populatie": 14177,
		"site": "http://www.comunaciurea.ro/"
	},
	"COARNELE CAPREI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Coarnele Caprei.pdf",
		"primar": "Grigoras Constantin",
		"s_p": 6525,
		"c_p": 4.5,
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.2,
		"s_s": 4640,
		"populatie": 3057,
		"site": "https://coarnelecaprei.ro/"
	},
	"COMARNA": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Comarna.pdf",
		"primar": "Gradinaru Constantin",
		"c_p": 5,
		"s_p": 7250,
		"c_vp": 4,
		"s_vp": 5800,
		"s_s": 4640,
		"c_s": 3.2,
		"populatie": 5405,
		"site": "http://www.primariacomarna.ro/"
	},
	"COSTESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Costesti.pdf",
		"primar": "Doaca Aurel",
		"s_p": 5800,
		"c_p": 4,
		"s_vp": 4828.5,
		"c_vp": 3.33,
		"s_s": null,
		"c_s": 0,
		"populatie": 1849,
		"site": "http://www.primariacomuneicostesti.ro/"
	},
	"COSTULENI": {
		"partid": "UNPR",
		"type": "Comuna",
		"raspuns": null,
		"primar": "Dodan Mirica",
		"populatie": 5065,
		"s_p": 0,
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://www.costuleni.primarii-iasi.ro/"
	},
	"COTNARI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Cotnari.pdf",
		"primar": "Cretu Vasile",
		"s_p": 7250,
		"c_p": 5,
		"s_vp": 5800,
		"c_vp": 4,
		"s_s": 5655,
		"c_s": 3.9,
		"populatie": 7999,
		"site": "http://www.primaria-cotnari.ro/"
	},
	"COZMESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": ["./raspunsuri_primarii/Cozmesti 1.jpeg", "./raspunsuri_primarii/Cozmesti 2.jpeg", "./raspunsuri_primarii/Cozmesti 3.jpeg", "./raspunsuri_primarii/Cozmesti 4.jpeg", "./raspunsuri_primarii/Cozmesti 5.jpeg", "./raspunsuri_primarii/Cozmesti 6.jpeg"],
		"primar": "Baltag Petrica",
		"s_p": 6525,
		"c_p": 4.5,
		"s_vp": 5075,
		"c_vp": 3.5,
		"s_s": 5075,
		"c_s": 3.5,
		"populatie": 2894,
		"site": "http://www.comunacozmesti.ro/"
	},
	"CRISTESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Cristesti.doc",
		"primar": "Bolohan Constantin",
		"populatie": 4105,
		"s_s": 5075,
		"c_p": 4.5,
		"s_p": 6525,
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.5,
		"site": "http://www.primariacomuneicristesti.ro/"
	},
	"CUCUTENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Cucuteni.doc",
		"primar": "Brînza Pamfilica",
		"populatie": 1315,
		"c_p": 4,
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 2.97,
		"s_s": 4306.5,
		"s_p": 5800,
		"site": "http://www.primariacucuteni.ro/"
	},
	"DAGATA": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Dagata.pdf",
		"populatie": 4955,
		"primar": "Damaschin Mirel",
		"s_vp": 5075,
		"s_s": 5021.35,
		"c_p": 4.5,
		"s_p": 6525,
		"c_vp": 3.5,
		"c_s": 3.463,
		"site": "http://primariadagata.ro/"
	},
	"DELENI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Delenei.jpg",
		"populatie": 10528,
		"c_p": 6.875,
		"s_p": 9969,
		"primar": "Prigoreanu Dumitru",
		"c_vp": 4.5,
		"s_vp": 6525,
		"c_s": 4.25,
		"s_s": 6162.5,
		"site": "http://comunadeleni.com/"
	},
	"DOBROVAT": {
		"partid": "PSD",
		"partial": true,
		"type": "Comuna",
		"raspuns": ["./raspunsuri_primarii/Dobrovat 1.png", "./raspunsuri_primarii/Dobrovat 2.png", "./raspunsuri_primarii/Dobrovat.pdf"],
		"populatie": 2426,
		"s_p": 0,
		"primar": "Martinus Catalin-iulian",
		"s_vp": 0,
		"c_s": 3,
		"s_s": 4350,
		"c_p": 0,
		"c_vp": 0,
		"site": "http://primariadobrovat.ro/"
	},
	"DOLHESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Dolhesti.pdf",
		"populatie": 2854,
		"c_p": 4,
		"s_p": 5800,
		"primar": "Iacob Gelu",
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 2.98,
		"s_s": 4321,
		"site": "http://www.dolhesti-iasi.ro/"
	},
	"DRAGUSENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Draguseni.pdf",
		"populatie": 1522,
		"c_p": 4,
		"s_p": 5800,
		"primar": "Ciobotaru Viorel",
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 2.9,
		"s_s": 4205,
		"site": "http://www.comunadraguseni.ro/index.php"
	},
	"DUMESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 5087,
		"s_p": 0,
		"primar": "Sabaiduc Mihai",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"ERBICENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 5757,
		"s_p": 0,
		"primar": "Lungu Ionel",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"FANTANELE": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Fantanele.pdf",
		"populatie": 2120,
		"c_p": 4,
		"s_p": 5800,
		"primar": "Chelariu Sorin",
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 3.99,
		"s_s": 5785.5,
		"site": "http://comunafantaneleiasi.ro/"
	},
	"FOCURI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Focuri.JPG",
		"populatie": 4092,
		"s_p": 6525,
		"primar": "Macovei Vasile",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.45,
		"s_s": 5002.5,
		"c_p": 4.5,
		"site": "http://comunafocuri.ro/"
	},
	"GOLAIESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Golaesti.pdf",
		"populatie": 4001,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Bîzdîga Mihai",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.49,
		"s_s": 5060.5,
		"site": "http://www.primariagolaiesti.ro/"
	},
	"GORBAN": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Gorban.pdf",
		"populatie": 3063,
		"c_p": 5.625,
		"s_p": 8156,
		"primar": "Rotaru Danut",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 0,
		"s_s": null
	},
	"GRAJDURI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Grajduri.pdf",
		"populatie": 7958,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Zamfirache Constantin",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.86,
		"s_s": 5597,
		"site": "http://www.primariagrajduri.ro/"
	},
	"GROPNITA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Gropnita.PDF",
		"populatie": 3366,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Oneaga Ionel",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.5,
		"s_s": 5075
	},
	"GROZESTI": {
		"partid": "PMP",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Grozesti.tif",
		"populatie": 1765,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Cristea George",
		"c_vp": 3.75,
		"s_vp": 5438,
		"c_s": 2.95,
		"s_s": 4278
	},
	"HALAUCESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 5867,
		"s_p": 0,
		"primar": "Anton Iosif",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://www.primariahalaucesti.ro/"
	},
	"HARMANESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": ["./raspunsuri_primarii/Harmanesti 1.pdf", "./raspunsuri_primarii/Harmanesti 2.pdf"],
		"populatie": 2476,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Secrieru Ioan",
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 2.99,
		"s_s": 4335.5,
		"site": "http://www.primaria-harmanesti.ro/"
	},
	"HARLAU": {
		"partid": "PSD",
		"type": "Orasul",
		"raspuns": "./raspunsuri_primarii/Harlau.pdf",
		"populatie": 12456,
		"c_p": 6,
		"s_p": 8700,
		"primar": "Curca Gheorghita",
		"c_vp": 5,
		"s_vp": 7250,
		"c_s": 4.25,
		"s_s": 6162.5,
		"site": "http://primaria-hirlau.ro/"
	},
	"HELESTENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Helesteni.pdf",
		"populatie": 2772,
		"c_p": 4,
		"s_p": 5800,
		"primar": "Hîra Constantin",
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 2.9,
		"s_s": 4205,
		"site": "http://www.primariahelesteni.ro/"
	},
	"HOLBOCA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Holboca.pdf",
		"populatie": 14774,
		"c_p": 5.5,
		"s_p": 7975,
		"primar": "Stefurac Gheorghe",
		"c_vp": 4.5,
		"s_vp": 6525,
		"c_s": 4.47,
		"s_s": 6481.5,
		"site": "http://www.comunaholboca.ro/"
	},
	"HORLESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Horlesti.pdf",
		"populatie": 3141,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Cadar Mihai",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 0,
		"s_s": null,
		"site": "http://comunahorlesti.ro/"
	},
	"IASI": {
		"partid": "PSD",
		"type": "Municipiul",
		"raspuns": "./raspunsuri_primarii/Iasi.pdf",
		"populatie": 359843,
		"c_p": 9,
		"s_p": 13050,
		"primar": "Mihai Chirica",
		"c_vp": 8,
		"s_vp": 11600,
		"c_s": null,
		"s_s": null,
		"site": "http://www.primaria-iasi.ro/"
	},
	"ION NECULCE": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Ion Neculce.pdf",
		"populatie": 5834,
		"c_p": 6.25,
		"s_p": 9063,
		"primar": "Valeanu Gheorghe",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 4,
		"s_s": 5800,
		"site": "https://primaria-ionneculce.ro/"
	},
	"IPATELE": {
		"partid": "PSD",
		"type": "Comuna",
		"partial": true,
		"raspuns": "./raspunsuri_primarii/Ipatele.pdf",
		"populatie": 1842,
		"s_p": 0,
		"primar": "Postarnac Costica",
		"s_vp": 0,
		"c_s": 2.9,
		"s_s": 4205,
		"c_p": 0,
		"c_vp": 0
	},
	"LESPEZI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Lespezi.doc",
		"populatie": 6032,
		"s_p": 9063,
		"primar": "Lazar Ioan",
		"s_vp": 7250,
		"s_s": 5727.5,
		"c_p": 6.25,
		"c_vp": 5,
		"c_s": 3.95,
		"site": "http://www.primarialespezi.ro/"
	},
	"LETCANI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Letcani.pdf",
		"populatie": 7633,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Turcu Stelian",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.8,
		"s_s": 5510,
		"site": "http://comunaletcani.ro/"
	},
	"LUNGANI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Lungani.docx",
		"populatie": 6295,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Pricopie Gheorghe",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.999,
		"s_s": 5798.55,
		"site": "http://lungani.primarii-iasi.ro/"
	},
	"MADIRJAC": {
		"partid": "UNPR",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 1681,
		"s_p": 0,
		"primar": "Ghebuta Dan",
		"s_vp": 0,
		"s_s": 0,
		"site": "http://www.madarjac.primarii-iasi.ro/",
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"MIRCESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Mircesti.PDF",
		"populatie": 3950,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Antalut Petre",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.48,
		"s_s": 5046,
		"site": "http://www.comunamircesti.ro/"
	},
	"MIRONEASA": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Mironeasa.pdf",
		"populatie": 5625,
		"s_p": 7250,
		"primar": "Curcudel Elena",
		"s_vp": 5800,
		"s_s": 5756.5,
		"c_p": 5,
		"c_vp": 4,
		"c_s": 3.97,
		"site": "http://www.mironeasa.webgarden.ro/"
	},
	"MIROSLAVA": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Miroslava.pdf",
		"populatie": 15055,
		"s_p": 0,
		"primar": "Nita Dan",
		"s_vp": 0,
		"s_s": 0,
		"site": "http://www.primariamiroslava.ro/",
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"MIROSLOVESTI": {
		"partid": "UNPR",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Miroslovesti.pdf",
		"populatie": 4532,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Cojocaru Constantin",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.4,
		"s_s": 4930,
		"site": "https://www.comunamiroslovesti.ro/"
	},
	"MOGOSESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Mogosesti.pdf",
		"populatie": 5333,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Maftei Stefan",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3,
		"s_s": 4988,
		"site": "http://www.mogosesti-primaria.ro/"
	},
	"MOGOSESTI-SIRET": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Mogosesti-siret.pdf",
		"populatie": 3863,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Butnariu Damian",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.49,
		"s_s": 5060.5,
		"site": "http://www.mogosesti-siret.ro/"
	},
	"MOSNA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Mosna.pdf",
		"populatie": 6210,
		"c_p": 6.25,
		"s_p": 9063,
		"primar": "Popa Georgel",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.5,
		"s_s": 5075,
		"site": "http://www.mosnaiasi.ro/"
	},
	"MOTCA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 5496,
		"s_p": 0,
		"primar": "Hobinca Constantin-serioja",
		"s_vp": 0,
		"s_s": 0,
		"site": "http://comunamotca.ro/",
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"MOVILENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Movileni.pdf",
		"populatie": 3180,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Plumbu Mihai",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 0,
		"s_s": null,
		"site": "http://www.primariamovileni.ro/"
	},
	"OTELENI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Oteleni.jpg",
		"populatie": 3777,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Aiojoaei Ciprian",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.4,
		"s_s": 4930,
		"site": "http://primariaoteleni.ro/"
	},
	"PASCANI": {
		"partid": "PSD",
		"type": "Municipiul",
		"raspuns": "./raspunsuri_primarii/Pascani.pdf",
		"populatie": 43555,
		"c_p": 6.5,
		"s_p": 9425,
		"primar": "Dumitru Pantazi",
		"c_vp": 5.5,
		"s_vp": 7975,
		"s_s": 0,
		"site": "http://primariapascani.ro/primarie/",
		"c_s": 0
	},
	"PLUGARI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Plugari.PDF",
		"populatie": 3555,
		"c_p": 5.625,
		"s_p": 8156,
		"primar": "Mursa Paul",
		"c_vp": 4.375,
		"s_vp": 6344,
		"s_s": 0,
		"site": "http://comunaplugari.ro/",
		"c_s": 0
	},
	"PODU ILOAIEI": {
		"partid": "PSD",
		"type": "Orasul",
		"raspuns": "./raspunsuri_primarii/Podu ilioaiei.pdf",
		"populatie": 11003,
		"s_p": 8700,
		"primar": "Gabi Constantin Istrate",
		"c_vp": 5,
		"s_vp": 7250,
		"s_s": 5474,
		"c_p": 6,
		"c_s": 3.77
	},
	"POPESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 5084,
		"s_p": 0,
		"primar": "Lupu Vasile",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://primariapopestiiasi.ro/"
	},
	"POPRICANI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Popricani.pdf",
		"populatie": 8238,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Parlog Valeriu",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.9,
		"s_s": 5655,
		"site": "http://primariapopricani.ro/"
	},
	"PRISACANI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Prisacani.pdf",
		"populatie": 3489,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Stanciu Ghiorghe",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.38,
		"s_s": 4901,
		"site": "http://www.prisacani.ro/"
	},
	"PROBOTA": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Probota.pdf",
		"populatie": 3775,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Zamisnicu Constantin",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.3,
		"s_s": 4785,
		"site": "http://www.primariaprobota.ro/"
	},
	"RACHITENI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 3443,
		"s_p": 0,
		"primar": "Dobos Petre",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://primariarachiteni.ro/"
	},
	"RADUCANENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Raducaneni.pdf",
		"populatie": 9282,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Ilie Viorel",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.72,
		"s_s": 5394,
		"site": "https://www.comunaraducaneni.ro/"
	},
	"REDIU": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Rediu.pdf",
		"populatie": 5959,
		"s_p": 7250,
		"primar": "Haidau Vasile",
		"s_vp": 5800,
		"s_s": 5046,
		"c_p": 5,
		"c_vp": 4,
		"c_s": 3.48,
		"site": "http://www.primariarediu.ro/"
	},
	"ROMANESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 1866,
		"c_p": 0,
		"s_p": 0,
		"primar": "Stegariu Ioan",
		"s_vp": 0,
		"s_s": 0,
		"c_vp": 0,
		"c_s": 0
	},
	"ROSCANI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Roscani.doc",
		"populatie": 1557,
		"c_p": 4,
		"s_p": 5800,
		"primar": "Gheorghiu Ginovel",
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 2.9,
		"s_s": 4205,
		"site": "http://www.primariaroscani.ro/"
	},
	"RUGINOASA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Ruginoasa.pdf",
		"populatie": 6451,
		"c_p": 6.25,
		"s_p": 9063,
		"primar": "Nechifor Danut",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.99,
		"s_s": 5785.5,
		"site": "http://primaria-ruginoasa.ro/"
	},
	"SCANTEIA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/scinteia.pdf",
		"populatie": 5268,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Sacaleanu Fanica",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.75,
		"s_s": 5437.5,
		"site": "http://www.primariascinteia.ro/"
	},
	"SCHEIA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Scheia.pdf",
		"populatie": 3402,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Ababei Danut",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.4,
		"s_s": 4930,
		"site": "http://www.scheia.ro/"
	},
	"SCHITU DUCA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 4156,
		"s_p": 0,
		"primar": "Mihalache Mihai",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://primariaschituduca.ro/"
	},
	"SCOBINTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Scobinti.pdf",
		"populatie": 7681,
		"s_p": 7250,
		"primar": "Hritcu Gheorghe",
		"s_vp": 5800,
		"s_s": 4712.5,
		"c_p": 5,
		"c_vp": 4,
		"c_s": 3.25,
		"site": "http://www.primariascobinti.ro/"
	},
	"SINESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Sinesti.pdf",
		"populatie": 4622,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Holicov Petru",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.45,
		"s_s": 5002.5,
		"site": "http://www.primariasinesti.ro/"
	},
	"SIPOTE": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/sipote.pdf",
		"populatie": 5346,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Malii Dorin- Mircea",
		"c_vp": 4,
		"s_vp": 5800,
		"s_s": 0,
		"site": "http://www.primariasipote.ro/",
		"c_s": 0
	},
	"SIRETEL": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 4380,
		"s_p": 0,
		"primar": "Ancuta Gheorghe",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "https://www.siretel.ro/"
	},
	"STOLNICENI-PRAJESCU": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Stolniceni.pdf",
		"populatie": 5533,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Hugianu Costel",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.98,
		"s_s": 5771,
		"site": "https://www.stolniceni.ro/"
	},
	"STRUNGA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 4480,
		"s_p": 0,
		"primar": "Lazar Mariana",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://primaria-strunga.ro/"
	},
	"TANSA": {
		"partid": "PNL",
		"partial": true,
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Tansa.pdf",
		"populatie": 2600,
		"s_p": 0,
		"primar": "Voinescu Daniel",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://www.primariatansa.ro/"
	},
	"TARGU FRUMOS": {
		"partid": "PSD",
		"type": "Orasul",
		"raspuns": "./raspunsuri_primarii/Tirgu Frumos.pdf",
		"populatie": 14562,
		"c_p": 6,
		"s_p": 8700,
		"primar": "Ionel Vatamanu",
		"c_vp": 5,
		"s_vp": 7250,
		"c_s": 3.95,
		"s_s": 5727.5,
		"site": "http://primariatgfrumos.ro/"
	},
	"TATARUSI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Tatarusi.pdf",
		"populatie": 5650,
		"s_p": 9063,
		"primar": "Iosub Costel",
		"s_vp": 7250,
		"s_s": 7148,
		"c_p": 6.25,
		"c_vp": 5,
		"c_s": 4.925,
		"site": "http://www.tatarusi.ro/"
	},
	"TIBANA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Tibana.pdf",
		"populatie": 8144,
		"c_p": 4.64,
		"s_p": 6728,
		"primar": "Rotaru Gheorghe",
		"c_vp": 4.08,
		"s_vp": 5916,
		"s_s": 7562,
		"c_s": 5.21,
		"site": " Spor confident"
	},
	"TIBANESTI": {
		"partid": "PSD",
		"partial": true,
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Tibanesti 1.pdf",
		"populatie": 8275,
		"s_p": 0,
		"primar": "Cobuz Aurica",
		"s_vp": 0,
		"c_s": 4,
		"s_s": 5800,
		"c_p": 0,
		"c_vp": 0,
		"site": "http://www.primariatibanesti.ro/"
	},
	"TIGANASI": {
		"partid": "PSD",
		"partial": true,
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Tiganasi.pdf",
		"populatie": 4776,
		"s_p": 0,
		"primar": "Chirila Iulian",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://www.primariatiganasi.ro/"
	},
	"TODIRESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 5351,
		"s_p": 0,
		"primar": "Droanca Ovidiu",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://www.primariatodiresti.ro/"
	},
	"TOMESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Tomesti.pdf",
		"populatie": 13896,
		"c_p": 5.5,
		"s_p": 7975,
		"primar": "Timofte Stefan",
		"c_vp": 4.5,
		"s_vp": 6525,
		"c_s": 4,
		"s_s": 5800,
		"site": "http://www.comuna-tomesti.ro/"
	},
	"TRIFESTI": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 4010,
		"s_p": 0,
		"primar": "Ivanuca Alexandru",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://primariatrifestiiasi.ro/"
	},
	"TUTORA": {
		"partid": "UNPR",
		"type": "Comuna",
		"raspuns": ["./raspunsuri_primarii/Tutora 1.pdf", "./raspunsuri_primarii/Tutora 2.pdf", "./raspunsuri_primarii/Tutora 3.pdf", "./raspunsuri_primarii/Tutora 4.pdf", "./raspunsuri_primarii/Tutora 5.pdf", "./raspunsuri_primarii/Tutora 6.pdf"],
		"populatie": 2152,
		"c_p": 4,
		"s_p": 5800,
		"primar": "Albu Cristinel",
		"c_vp": 3,
		"s_vp": 4350,
		"c_s": 3,
		"s_s": 4350,
		"site": "http://www.primariatutora.ro/"
	},
	"UNGHENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Ungheni.jpeg",
		"populatie": 4436,
		"c_p": 4.5,
		"s_p": 6525,
		"primar": "Marcu Iulian",
		"c_vp": 3.5,
		"s_vp": 5075,
		"c_s": 3.49,
		"s_s": 5060.5,
		"site": "http://www.comunaungheni.ro/"
	},
	"VALEA LUPULUI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Valea Lupului.pdf",
		"populatie": 6171,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Mihailuc Dumitru",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.97,
		"s_s": 5756.5,
		"site": "http://comuna-valealupului.ro/"
	},
	"VALEA SEACA": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Valea Seaca.pdf",
		"populatie": 6180,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Baiceanu Gheorghe",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.97,
		"s_s": 5756.5,
		"site": "http://primariavaleaseaca.ro/"
	},
	"VANATORI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 4737,
		"s_p": 0,
		"primar": "Lupu Constantin",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://www.primariavanatori.ro/"
	},
	"VICTORIA": {
		"partid": "PNL",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/VICTORIA.pdf",
		"populatie": 4524,
		"c_p": 5.625,
		"s_p": 8156,
		"primar": "Cretu Daniel",
		"c_vp": 4.375,
		"s_vp": 6344,
		"c_s": 3.5,
		"s_s": 5075,
		"site": "http://comunavictoria.ro/"
	},
	"VLADENI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": null,
		"populatie": 4434,
		"s_p": 0,
		"primar": "Brînzanu Catalin",
		"s_vp": 0,
		"s_s": 0,
		"c_p": 0,
		"c_vp": 0,
		"c_s": 0,
		"site": "http://vladeni.primarii-iasi.ro/"
	},
	"VOINESTI": {
		"partid": "PSD",
		"type": "Comuna",
		"raspuns": "./raspunsuri_primarii/Voinesti.pdf",
		"populatie": 8046,
		"c_p": 5,
		"s_p": 7250,
		"primar": "Dobreanu Gheorghe",
		"c_vp": 4,
		"s_vp": 5800,
		"c_s": 3.96,
		"s_s": 5742,
		"site": "http://primariavoinesti-iasi.ro/drupal/"
	}
}
