
detalii_primarii = {
    "ALEXANDRU IOAN CUZA":{ partid : "PSD", type:"Comuna",raspuns: null },
	"ANDRIESENI":{ partid :"PNL",raspuns: null },
	"ARONEANU":{ partid :"PNL",raspuns: null },
	"BALS":{ partid :"PSD", salariu_p: 6525, salariu_vp: 5075, salariu_s: 5060 ,raspuns: ["./raspunsuri_primarii/bals1.pdf", "./raspunsuri_primarii/bals2.pdf"]},
	"BALTATI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Baltati.pdf" },
	"BARNOVA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Barnova.pdf" },
	"BELCESTI":{ partid :"PNL",raspuns: null },
	"BIVOLARI":{ partid :"PSD",raspuns: null },
	"BRAESTI":{ partid :"PNL",raspuns: null },
	"BUTEA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Butea.pdf" },
	"CEPLENITA":{ partid :"PNL",raspuns: null },
	"CIOHORANI":{ partid :"PSD",raspuns: null },
	"CIORTESTI":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Ciortesti.xls" },
	"CIUREA":{ partid :"PSD", partial:true, raspuns: ["./raspunsuri_primarii/Ciurea 1.bmp", "./raspunsuri_primarii/Ciurea 2.bmp", "./raspunsuri_primarii/Ciurea 3.bmp"] },
	"COARNELE CAPREI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Coarnele Caprei.pdf" },
	"COMARNA":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Comarna.pdf" },
	"COSTESTI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Costesti.pdf" },
	"COSTULENI":{ partid :"UNPR",raspuns: null },
	"COTNARI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Cotnari.pdf" },
	"COZMESTI":{ partid :"PSD",raspuns: null },
	"CRISTESTI":{ partid :"PSD",raspuns: null },
	"CUCUTENI":{ partid :"PSD",raspuns: null },
	"DAGATA":{ partid :"PNL",raspuns: null },
	"DELENI":{ partid :"PNL",raspuns: null },
	"DOBROVAT":{ partid :"PSD", partial:true, raspuns: ["./raspunsuri_primarii/Dobrovat 1.png", "./raspunsuri_primarii/Dobrovat 2.png", "./raspunsuri_primarii/Dobrovat.pdf"] },
	"DOLHESTI":{ partid :"PNL",raspuns: null },
	"DRAGUSENI":{ partid :"PSD",raspuns: null },
	"DUMESTI":{ partid :"PSD",raspuns: null },
	"ERBICENI":{ partid :"PSD",raspuns: null },
	"FANTANELE":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Fantanele.pdf" },
	"FOCURI":{ partid :"PSD",raspuns: null },
	"GOLAIESTI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Golaesti.pdf" },
	"GORBAN":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Gorban.pdf" },
	"GRAJDURI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Grajduri.pdf" },
	"GROPNITA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Gropnita.PDF" },
	"GROZESTI":{ partid :"PMP",raspuns: null },
	"HALAUCESTI":{ partid :"PNL",raspuns: null },
	"HARMANESTI":{ partid :"PNL",raspuns: ["./raspunsuri_primarii/Harmanesti 1.pdf", "./raspunsuri_primarii/Harmanesti 2.pdf"] },
	"HARLAU":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Harlau.pdf" },
	"HELESTENI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Helesteni.pdf" },
	"HOLBOCA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Holboca.pdf" },
	"HORLESTI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Horlesti.pdf" },
	"IASI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Iasi.pdf" },
	"ION NECULCE":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Ion Neculce.pdf" },
	"IPATELE":{ partid :"PSD", partial: true, raspuns: "./raspunsuri_primarii/Ipatele.pdf" },
	"LESPEZI":{ partid :"PNL",raspuns: null },
	"LETCANI":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Letcani.pdf"  },
	"LUNGANI":{ partid :"PSD",raspuns: null },
	"MADIRJAC":{ partid :"UNPR",raspuns: null },
	"MIRCESTI":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Mircesti.PDF" },
	"MIRONEASA":{ partid :"PNL",raspuns: null },
	"MIROSLAVA":{ partid :"PNL",raspuns: null },
	"MIROSLOVESTI":{ partid :"UNPR",raspuns: "./raspunsuri_primarii/Miroslovesti.pdf" },
	"MOGOSESTI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Mogosesti.pdf" },
	"MOGOSESTI-SIRET":{ partid :"PNL",raspuns: null },
	"MOSNA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Mosna.pdf" },
	"MOTCA":{ partid :"PSD",raspuns: null },
	"MOVILENI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Movileni.pdf" },
	"OTELENI":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Oteleni.jpg" },
	"PASCANI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Pascani.pdf" },
	"PLUGARI":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Plugari.PDF" },
	"PODU ILOAIEI":{ partid :"PSD",raspuns: null },
	"POPESTI":{ partid :"PNL",raspuns: null },
	"POPRICANI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Popricani.pdf" },
	"PRISACANI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Prisacani.pdf" },
	"PROBOTA":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Probota.pdf" },
	"RACHITENI":{ partid :"PNL",raspuns: null },
	"RADUCANENI":{ partid :"PSD",raspuns: null },
	"REDIU":{ partid :"PNL",raspuns: null },
	"ROMANESTI":{ partid :"PNL",raspuns: null },
	"ROSCANI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Roscani.doc" },
	"RUGINOASA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Ruginoasa.pdf" },
	"SCANTEIA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/scinteia.pdf" },
	"SCHEIA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Scheia.pdf" },
	"SCHITU DUCA":{ partid :"PSD",raspuns: null },
	"SCOBINTI":{ partid :"PSD",raspuns: null },
	"SINESTI":{ partid :"PNL",raspuns: "./raspunsuri_primarii/Sinesti.pdf" },
	"SIPOTE":{ partid :"PSD",raspuns: "./raspunsuri_primarii/sipote.pdf" },
	"SIRETEL":{ partid :"PNL",raspuns: null },
	"STOLNICENI-PRAJESCU":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Stolniceni.pdf" },
	"STRUNGA":{ partid :"PSD",raspuns: null },
	"TANSA":{ partid :"PNL", partial: true, raspuns: "./raspunsuri_primarii/Tansa.pdf" },
	"TARGU FRUMOS":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Tirgu Frumos.pdf" },
	"TATARUSI":{ partid :"PSD",raspuns: null },
	"TIBANA":{ partid :"PSD",raspuns: null },
	"TIBANESTI":{ partid :"PSD", partial:true, raspuns: "./raspunsuri_primarii/Tibanesti 1.pdf" },
	"TIGANASI":{ partid :"PSD", partial:true, raspuns: "./raspunsuri_primarii/Tiganasi.pdf" },
	"TODIRESTI":{ partid :"PSD",raspuns: null },
	"TOMESTI":{ partid :"PSD",salariu_2017: 50000 ,raspuns: "./raspunsuri_primarii/Tomesti.pdf" },
	"TRIFESTI":{ partid :"PNL",raspuns: null },
	"TUTORA":{ partid :"UNPR",raspuns: ["./raspunsuri_primarii/Tutora 1.pdf","./raspunsuri_primarii/Tutora 2.pdf","./raspunsuri_primarii/Tutora 3.pdf","./raspunsuri_primarii/Tutora 4.pdf","./raspunsuri_primarii/Tutora 5.pdf", "./raspunsuri_primarii/Tutora 6.pdf" ] },
	"UNGHENI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Ungheni.jpeg" },
	"VALEA LUPULUI":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Valea Lupului.pdf" },
	"VALEA SEACA":{ partid :"PSD",raspuns: "./raspunsuri_primarii/Valea Seaca.pdf" },
	"VANATORI":{ partid :"PSD",raspuns: null },
	"VICTORIA":{ partid :"PNL",raspuns:"./raspunsuri_primarii/VICTORIA.pdf" },
	"VLADENI":{ partid :"PSD",raspuns: null },
	"VOINESTI":{ partid :"PSD", raspuns:"./raspunsuri_primarii/Voinesti.pdf"}
}